# Generated by Django 4.1.4 on 2022-12-25 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('auther', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('createDate', models.DateField(auto_now_add=True)),
                ('buy', models.BooleanField(default=False)),
                ('review', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['buy'],
            },
        ),
    ]
