# Generated by Django 4.1.4 on 2023-01-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRecordApp', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to='', width_field=50),
        ),
    ]
