# Generated by Django 4.1.4 on 2023-01-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRecordApp', '0003_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='', width_field=150),
        ),
    ]
