# Generated by Django 4.1.4 on 2023-01-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRecordApp', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
